/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.istloja.vistas;

import com.istloja.controlador.Inventariodb;
import com.istloja.controlador.Personabd;
import com.istloja.controlador.Proveedoresdb;
import com.istloja.modelTables.ModelTablePersona;
import com.istloja.modelTables.ModelTablePersonaV2;
import com.istloja.modelo.Persona;
import com.istloja.modelo.Proveedores;
import com.istloja.utilidad.Utilidades;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import com.istloja.modelTables.ComunicacionVistaModelosTablas;
import com.istloja.modelTables.ModelTableInventario;
import com.istloja.modelTables.ModelTableProveedores;
import com.istloja.modelo.Inventario;
import java.awt.event.ItemEvent;
import java.util.Date;

/**
 *
 * @author johnp
 */
public class GestionContable extends javax.swing.JFrame implements ComunicacionVistaModelosTablas {

    // Iconos Free https://www.flaticon.es/
    private Utilidades utilidades;
    private Personabd controladorPersona;
    private Persona personaEditarEliminar;
    private GestionPersona gestionPersona;
    //private ModelTablePersona modelTablePersona;
    private ModelTablePersonaV2 modelTablePersonaV2;
    private ModelTableProveedores modelTableProveedores;
    private ModelTableInventario modelTableInventario;
    private Proveedoresdb controladorProveedor;
    private Inventariodb controladorInventario;
    private Inventario inventarioSeleccionado;
    private Proveedores proveedorSelect;

    /**
     * Creates new form GestionPersonaV1
     */
    public GestionContable() {
        controladorPersona = new Personabd();
        controladorProveedor = new Proveedoresdb();
        controladorInventario = new Inventariodb();
        modelTablePersonaV2 = new ModelTablePersonaV2(controladorPersona.obtenerPersonas(), this);
        modelTableProveedores = new ModelTableProveedores(controladorProveedor.obtenerProveedores(), this);
        modelTableInventario = new ModelTableInventario(controladorInventario.obtenerProductosInventario(), this);
        initComponents();
        jrbCedula.setSelected(true);
        utilidades = new Utilidades();
        setLocationRelativeTo(null);
        gestionPersona = new GestionPersona(txtCedula, txtNombres, txtApellidos, txtDireccion, txtCorreo, txtTelefono, utilidades, this, jcboxGenero);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabGeneral = new javax.swing.JTabbedPane();
        panelCliente = new javax.swing.JPanel();
        txtTituloCliente = new javax.swing.JLabel();
        panelCuerpoRegistro = new javax.swing.JPanel();
        lblCedula = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jrbCedula = new javax.swing.JRadioButton();
        jrbPassaporte = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jcboxGenero = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jDateFechaNacimiento = new com.toedter.calendar.JDateChooser();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollCliente = new javax.swing.JScrollPane();
        tablaCliente = new javax.swing.JTable();
        lblBuscarCliente = new javax.swing.JLabel();
        comboParametroBusqueda = new javax.swing.JComboBox<>();
        txtParametroBusqueda = new javax.swing.JTextField();
        panelProveedores = new javax.swing.JPanel();
        txtTituloProveedores = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRucProveedores = new javax.swing.JTextField();
        txtRazonSocialProveedores = new javax.swing.JTextField();
        txtTipoActividadProveedores = new javax.swing.JTextField();
        txtNombreRepresentateLegalProveedores = new javax.swing.JTextField();
        txtApellidosRepresentateLegalProveedores = new javax.swing.JTextField();
        txtTelefonoProveedores = new javax.swing.JTextField();
        txtCorrreoProveedores = new javax.swing.JTextField();
        btnGuardarProveedores = new javax.swing.JButton();
        btnEditarProveedores = new javax.swing.JButton();
        btnElimnarProveedores = new javax.swing.JButton();
        btnLimpiarProveedor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProvedores = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        comboParamtroBusquedaProveedor = new javax.swing.JComboBox<>();
        txtParametroBusquedaProveedor = new javax.swing.JTextField();
        btnBuscarProveedor = new javax.swing.JButton();
        panelInventario = new javax.swing.JPanel();
        txtTituloInventario = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtInventarioCodProducto = new javax.swing.JTextField();
        txtInventarioDescripcion = new javax.swing.JTextField();
        txtPrecioCompra = new javax.swing.JTextField();
        txtInventarioCantidadProdcutos = new javax.swing.JTextField();
        btnInventarioCrear = new javax.swing.JButton();
        btnInventarioEditar = new javax.swing.JButton();
        btnInventarioEliminar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtPrecioConIva = new javax.swing.JTextField();
        txtPrecioMayorista = new javax.swing.JTextField();
        txtPrecioClienteFijo = new javax.swing.JTextField();
        txtPrecioClienteNormal = new javax.swing.JTextField();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        btnLimpiarInventario = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        comboBoxInventarioBusqueda = new javax.swing.JComboBox<>();
        txtInventarioBusqueda = new javax.swing.JTextField();
        btnInventaripBusqueda = new javax.swing.JButton();
        tblInventario = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelVenta = new javax.swing.JPanel();
        txtTituloVenta = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtBuscarClienteNotaVenta = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtDireccionNotaVenta = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtNombreClienteNotaVenta = new javax.swing.JTextField();
        txtTelefonoNotaVenta = new javax.swing.JTextField();
        txtFechaVentaNotaVenta = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        txtCantidadProuductoNotaVenta = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtIdProductoNotaVenta = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        menuGeneral = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuBuscarPersona = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA DE VENTAS");

        txtTituloCliente.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtTituloCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/istloja/resource/img/customer-cliente.png"))); // NOI18N
        txtTituloCliente.setText("   REGISTRO CLIENTES");

        panelCuerpoRegistro.setBorder(javax.swing.BorderFactory.createTitledBorder("Cuerpo Registro"));

        lblCedula.setText("DNI:");

        lblNombre.setText("NOMBRES:");

        lblApellido.setText("APELLIDOS:");

        lblDireccion.setText("DIRECCIÓN:");

        lblTelefono.setText("TELÉFONO:");

        lblCorreo.setText("CORREO:");

        txtCedula.setToolTipText("Ingrese una cédula correcta.");
        txtCedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCedulaFocusLost(evt);
            }
        });

        jrbCedula.setText("CEDÚLA");
        jrbCedula.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jrbCedulaItemStateChanged(evt);
            }
        });

        jrbPassaporte.setText("PASAPORTE");
        jrbPassaporte.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jrbPassaporteItemStateChanged(evt);
            }
        });

        jLabel15.setText("GENERO:");

        jcboxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No definifo", "Hombre", "Mujer" }));

        jLabel16.setText("FECHA NACIMIENTO:");

        javax.swing.GroupLayout panelCuerpoRegistroLayout = new javax.swing.GroupLayout(panelCuerpoRegistro);
        panelCuerpoRegistro.setLayout(panelCuerpoRegistroLayout);
        panelCuerpoRegistroLayout.setHorizontalGroup(
            panelCuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuerpoRegistroLayout.createSequentialGroup()
                .addGroup(panelCuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCuerpoRegistroLayout.createSequentialGroup()
                        .addGroup(panelCuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCuerpoRegistroLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(panelCuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblApellido)
                                    .addComponent(lblCedula)
                                    .addComponent(lblNombre)))
                            .addComponent(lblTelefono, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDireccion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCorreo, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCuerpoRegistroLayout.createSequentialGroup()
                        .addComponent(txtCedula)
                        .addGap(18, 18, 18)
                        .addComponent(jrbCedula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbPassaporte))
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 1305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidos)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCorreo)
                    .addComponent(txtDireccion)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jcboxGenero, 0, 1235, Short.MAX_VALUE)
                        .addComponent(jDateFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(1376, 1376, 1376))
        );
        panelCuerpoRegistroLayout.setVerticalGroup(
            panelCuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuerpoRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbCedula)
                    .addComponent(jrbPassaporte)
                    .addComponent(lblCedula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApellido))
                .addGap(18, 18, 18)
                .addGroup(panelCuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreo)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelCuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jcboxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jDateFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/istloja/resource/img/diskette.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/istloja/resource/img/pencil.png"))); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/istloja/resource/img/basura.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setPreferredSize(new java.awt.Dimension(141, 36));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/istloja/resource/img/limpiar.png"))); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setToolTipText("Limpiar Campos");
        btnLimpiar.setPreferredSize(new java.awt.Dimension(122, 36));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        tablaCliente.setModel(modelTablePersonaV2);
        jScrollCliente.setViewportView(tablaCliente);

        lblBuscarCliente.setText("Buscar Cliente");

        comboParametroBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cédula", "Nombres", "Apellidos", "Telefono", "Correo" }));

        txtParametroBusqueda.setToolTipText("Para realizar  busqueda ingrese alguna parametro.");
        txtParametroBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtParametroBusquedaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panelClienteLayout = new javax.swing.GroupLayout(panelCliente);
        panelCliente.setLayout(panelClienteLayout);
        panelClienteLayout.setHorizontalGroup(
            panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteLayout.createSequentialGroup()
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCuerpoRegistro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1629, Short.MAX_VALUE)
                    .addComponent(jScrollCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelClienteLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblBuscarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboParametroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtParametroBusqueda))
                    .addGroup(panelClienteLayout.createSequentialGroup()
                        .addContainerGap(1064, Short.MAX_VALUE)
                        .addComponent(btnGuardar)
                        .addGap(35, 35, 35)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addContainerGap())
            .addGroup(panelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTituloCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelClienteLayout.setVerticalGroup(
            panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTituloCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCuerpoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar)
                    .addComponent(btnGuardar))
                .addGap(41, 41, 41)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarCliente)
                    .addComponent(comboParametroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtParametroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        tabGeneral.addTab("CLIENTES", panelCliente);

        txtTituloProveedores.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtTituloProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/istloja/resource/img/crm-proveedor.png"))); // NOI18N
        txtTituloProveedores.setText("   REGISTRO PROVEEDORES");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Proveedor"));

        jLabel1.setText("RUC:");

        jLabel2.setText("RAZON SOCIAL:");

        jLabel3.setText("TIPO ACTIVIDAD:");

        jLabel4.setText("NOMBRE REPRESENTANTE LEGAL:");

        jLabel5.setText("APELLIDOS REPRESENTANTE LEGAL:");

        jLabel6.setText("TELEFONO:");

        jLabel7.setText("CORREO:");

        txtTelefonoProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoProveedoresActionPerformed(evt);
            }
        });

        btnGuardarProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/istloja/resource/img/diskette.png"))); // NOI18N
        btnGuardarProveedores.setText("Guardar");
        btnGuardarProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProveedoresActionPerformed(evt);
            }
        });

        btnEditarProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/istloja/resource/img/pencil.png"))); // NOI18N
        btnEditarProveedores.setText("Editar");
        btnEditarProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProveedoresActionPerformed(evt);
            }
        });

        btnElimnarProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/istloja/resource/img/basura.png"))); // NOI18N
        btnElimnarProveedores.setText("Eliminar");
        btnElimnarProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElimnarProveedoresActionPerformed(evt);
            }
        });

        btnLimpiarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/istloja/resource/img/limpiar.png"))); // NOI18N
        btnLimpiarProveedor.setText("LIMPIAR");
        btnLimpiarProveedor.setToolTipText("Limpiar Campos");
        btnLimpiarProveedor.setPreferredSize(new java.awt.Dimension(122, 36));
        btnLimpiarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRucProveedores)
                            .addComponent(txtRazonSocialProveedores, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTipoActividadProveedores, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNombreRepresentateLegalProveedores)
                            .addComponent(txtApellidosRepresentateLegalProveedores, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTelefonoProveedores, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCorrreoProveedores, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(1092, Short.MAX_VALUE)
                        .addComponent(btnGuardarProveedores)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarProveedores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnElimnarProveedores)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRucProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRazonSocialProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTipoActividadProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombreRepresentateLegalProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtApellidosRepresentateLegalProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTelefonoProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCorrreoProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnElimnarProveedores)
                    .addComponent(btnEditarProveedores)
                    .addComponent(btnGuardarProveedores)
                    .addComponent(btnLimpiarProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tablaProvedores.setModel(modelTableProveedores);
        jScrollPane1.setViewportView(tablaProvedores);

        jLabel8.setText("Buscador");

        comboParamtroBusquedaProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RUC", "RAZÓN SOCIAL", "TIPO ACTIVIDAD", "NOMBRE REPRESENTANTE LEGAL", " " }));

        btnBuscarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/istloja/resource/img/search.png"))); // NOI18N
        btnBuscarProveedor.setText("BUSCAR");

        javax.swing.GroupLayout panelProveedoresLayout = new javax.swing.GroupLayout(panelProveedores);
        panelProveedores.setLayout(panelProveedoresLayout);
        panelProveedoresLayout.setHorizontalGroup(
            panelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProveedoresLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProveedoresLayout.createSequentialGroup()
                        .addComponent(txtTituloProveedores)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProveedoresLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(36, 36, 36)
                        .addComponent(comboParamtroBusquedaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtParametroBusquedaProveedor)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarProveedor))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelProveedoresLayout.setVerticalGroup(
            panelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTituloProveedores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(panelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboParamtroBusquedaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtParametroBusquedaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProveedor)
                    .addComponent(jLabel8))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        tabGeneral.addTab("PROVEEDORES", panelProveedores);

        txtTituloInventario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtTituloInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/istloja/resource/img/inventory.png"))); // NOI18N
        txtTituloInventario.setText("   REGISTRO INVENTARIO");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Inventario"));

        jLabel9.setText("Codigo Producto:");

        jLabel10.setText("Descripción:");

        jLabel11.setText("Precio Compra:");

        jLabel13.setText("Cantidad prodcutos:");

        txtPrecioCompra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrecioCompraFocusLost(evt);
            }
        });
        txtPrecioCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrecioCompraKeyPressed(evt);
            }
        });

        btnInventarioCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/istloja/resource/img/diskette.png"))); // NOI18N
        btnInventarioCrear.setText("Crear");
        btnInventarioCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioCrearActionPerformed(evt);
            }
        });

        btnInventarioEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/istloja/resource/img/pencil.png"))); // NOI18N
        btnInventarioEditar.setText("Editar");
        btnInventarioEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioEditarActionPerformed(evt);
            }
        });

        btnInventarioEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/istloja/resource/img/basura.png"))); // NOI18N
        btnInventarioEliminar.setText("Eliminar");
        btnInventarioEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioEliminarActionPerformed(evt);
            }
        });

        jLabel17.setText("precio compra con IVA:");

        jLabel18.setText("Precio Mayorista:");

        jLabel19.setText("Precio cliente Fijo:");

        jLabel20.setText("Precio Cliente Normal:");

        jLabel21.setText("Fecha Caducidad:");

        txtPrecioConIva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioConIvaActionPerformed(evt);
            }
        });

        txtPrecioClienteNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioClienteNormalActionPerformed(evt);
            }
        });

        btnLimpiarInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/istloja/resource/img/limpiar.png"))); // NOI18N
        btnLimpiarInventario.setText("LIMPIAR");
        btnLimpiarInventario.setToolTipText("Limpiar Campos");
        btnLimpiarInventario.setPreferredSize(new java.awt.Dimension(122, 36));
        btnLimpiarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarInventarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel9))
                            .addComponent(jLabel11)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtInventarioCantidadProdcutos)
                            .addComponent(txtInventarioCodProducto)
                            .addComponent(txtInventarioDescripcion)
                            .addComponent(txtPrecioCompra)
                            .addComponent(txtPrecioClienteNormal)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecioConIva))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecioMayorista))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrecioClienteFijo))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnInventarioCrear)
                        .addGap(30, 30, 30)
                        .addComponent(btnInventarioEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnInventarioEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiarInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtInventarioCodProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtInventarioCantidadProdcutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtInventarioDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtPrecioConIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtPrecioMayorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtPrecioClienteFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addComponent(txtPrecioClienteNormal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel21))
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInventarioCrear)
                    .addComponent(btnInventarioEditar)
                    .addComponent(btnInventarioEliminar)
                    .addComponent(btnLimpiarInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel14.setText("Busqueda");

        comboBoxInventarioBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codigo Producto", "Descripcion" }));

        btnInventaripBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/istloja/resource/img/search.png"))); // NOI18N
        btnInventaripBusqueda.setText("Buscar");
        btnInventaripBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventaripBusquedaActionPerformed(evt);
            }
        });

        jTable1.setModel(modelTableInventario);
        tblInventario.setViewportView(jTable1);

        javax.swing.GroupLayout panelInventarioLayout = new javax.swing.GroupLayout(panelInventario);
        panelInventario.setLayout(panelInventarioLayout);
        panelInventarioLayout.setHorizontalGroup(
            panelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInventarioLayout.createSequentialGroup()
                .addGroup(panelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInventarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelInventarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tblInventario))
                    .addGroup(panelInventarioLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(txtTituloInventario)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelInventarioLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(comboBoxInventarioBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtInventarioBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 1258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnInventaripBusqueda)
                        .addGap(3, 3, 3)))
                .addContainerGap())
        );
        panelInventarioLayout.setVerticalGroup(
            panelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTituloInventario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(panelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(comboBoxInventarioBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInventarioBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInventaripBusqueda))
                .addGap(27, 27, 27)
                .addComponent(tblInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        tabGeneral.addTab("INVENTARIO", panelInventario);

        txtTituloVenta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtTituloVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/istloja/resource/img/bolsa-de-la-compra.png"))); // NOI18N
        txtTituloVenta.setText("   NOTA VENTA");

        jLabel12.setText("NÚMERO NOTA VENTA:");

        jLabel22.setText("CEDÚLA O RUC CLIENTE:");

        txtBuscarClienteNotaVenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscarClienteNotaVentaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscarClienteNotaVentaFocusLost(evt);
            }
        });

        jLabel23.setText("NOMBRE CLIENTE:");

        txtDireccionNotaVenta.setEditable(false);

        jLabel24.setText("DIRECCIÓN");

        jLabel25.setText("TELÉFONO:");

        jLabel26.setText("FECHA VENTA:");

        txtNombreClienteNotaVenta.setEditable(false);

        txtTelefonoNotaVenta.setEditable(false);

        txtFechaVentaNotaVenta.setEditable(false);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cant.", "Descripcion", "SubTotal", "Total"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel27.setText("ID PRODUCTO");

        jLabel28.setText("CANTIDAD");

        jButton1.setText("AGREGAR");

        jLabel29.setText("Sub TOtal");

        jLabel30.setText("IVA");

        jLabel31.setText("Total");

        jLabel32.setText("Tipo Pago");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta de credito", " " }));

        jButton2.setText("Busqueda Avanzada");

        javax.swing.GroupLayout panelVentaLayout = new javax.swing.GroupLayout(panelVenta);
        panelVenta.setLayout(panelVentaLayout);
        panelVentaLayout.setHorizontalGroup(
            panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentaLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(panelVentaLayout.createSequentialGroup()
                        .addGroup(panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelVentaLayout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addGap(27, 27, 27)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelVentaLayout.createSequentialGroup()
                                .addGroup(panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelVentaLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtTituloVenta)
                                    .addGroup(panelVentaLayout.createSequentialGroup()
                                        .addGroup(panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel23)
                                            .addComponent(jLabel25))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTelefonoNotaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtBuscarClienteNotaVenta)
                                            .addComponent(txtNombreClienteNotaVenta, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGap(18, 18, 18)
                                .addGroup(panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelVentaLayout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtFechaVentaNotaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelVentaLayout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addGap(38, 38, 38)
                                        .addComponent(txtDireccionNotaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 604, Short.MAX_VALUE)
                        .addGroup(panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVentaLayout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVentaLayout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVentaLayout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelVentaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel27)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdProductoNotaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel28)
                        .addGap(77, 77, 77)
                        .addComponent(txtCantidadProuductoNotaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        panelVentaLayout.setVerticalGroup(
            panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTituloVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtBuscarClienteNotaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtDireccionNotaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(txtNombreClienteNotaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(txtTelefonoNotaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaVentaNotaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(txtCantidadProuductoNotaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdProductoNotaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(226, Short.MAX_VALUE))
        );

        tabGeneral.addTab("VENTA", panelVenta);

        menuGeneral.setToolTipText("Limpiar formulario");

        menuArchivo.setText("Archivo");

        menuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(menuSalir);

        jMenu2.setText("Acciones Persona");

        menuBuscarPersona.setText("Buscar");
        menuBuscarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBuscarPersonaActionPerformed(evt);
            }
        });
        jMenu2.add(menuBuscarPersona);

        menuArchivo.add(jMenu2);

        menuGeneral.add(menuArchivo);

        menuEditar.setText("Editar");
        menuGeneral.add(menuEditar);

        jMenu1.setText("Acerca de");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        menuGeneral.add(jMenu1);

        setJMenuBar(menuGeneral);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabGeneral)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabGeneral)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void actualizarTodaLaTablaPersonas() {
        modelTablePersonaV2.setPersonas(controladorPersona.obtenerPersonas());
        modelTablePersonaV2.fireTableDataChanged();
    }

    public void actualizarTodaLaTablaProveedores() {
        modelTableProveedores.setProveedores(controladorProveedor.obtenerProveedores());
        modelTableProveedores.fireTableDataChanged();
    }

    public void buscarPersonaPorCedula() {
        Persona persona = controladorPersona.getPersonaCedula(txtCedula.getText());
        if (persona != null) {
            txtNombres.setText(persona.getNombre());
            txtApellidos.setText(persona.getApellidos());
            txtDireccion.setText(persona.getDireccion());
            txtCorreo.setText(persona.getCorreo());
            txtTelefono.setText(persona.getTelefono());
            personaEditarEliminar = persona;
        } else {
            JOptionPane.showMessageDialog(rootPane, "No se encontro la persona con ese número de cédula en la base de datos.", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtCedula.setText("");
            txtCedula.requestFocus();
        }
    }

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuBuscarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBuscarPersonaActionPerformed
        // TODO add your handling code here:
        buscarPersonaPorCedula();
    }//GEN-LAST:event_menuBuscarPersonaActionPerformed

    private void txtTelefonoProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoProveedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoProveedoresActionPerformed

    private void btnGuardarProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProveedoresActionPerformed
        // TODO add your handling code here:
        Proveedores proveedores = new Proveedores();
        proveedores.setRuc(txtRucProveedores.getText());
        proveedores.setRazonSocial(txtRazonSocialProveedores.getText());
        proveedores.setTipoActividad(txtTipoActividadProveedores.getText());
        proveedores.setNombreRepresentanteLegal(txtNombreRepresentateLegalProveedores.getText());
        proveedores.setApellidosRepresentanteLegal(txtApellidosRepresentateLegalProveedores.getText());
        proveedores.setTelefono(txtTelefonoProveedores.getText());
        proveedores.setCorreo(txtCorrreoProveedores.getText());
        proveedores.setFechaRegistro(new Date());
        proveedores.setFechaVencimientoDeuda(null);
        if (controladorProveedor.registrarProveedor(proveedores)) {
            JOptionPane.showMessageDialog(rootPane, "Proveedor guardado con éxito del sitema.");
            limpiarCamposProveedor();
            actualizarTodaLaTablaProveedores();
        } else {
            JOptionPane.showMessageDialog(rootPane, "No se puede guardar el proveedor.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarProveedoresActionPerformed

    private void btnInventarioEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioEliminarActionPerformed
        if (inventarioSeleccionado != null) {
            if (controladorInventario.eliminarInventario(inventarioSeleccionado)) {
                JOptionPane.showMessageDialog(rootPane, "Producto eliminado con éxito del sitema.");
                limpiarInventario();
                inventarioSeleccionado = null;
                modelTableInventario.setInventarios(controladorInventario.obtenerProductosInventario());
                modelTableInventario.fireTableDataChanged();
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se puede eliminar el producto seleccionado.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No hay producto seleccionada para eliminar.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInventarioEliminarActionPerformed

    private void btnInventarioEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioEditarActionPerformed
        if (inventarioSeleccionado == null) {
            JOptionPane.showMessageDialog(rootPane, "No hay una propducto seleccionado para editar", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (inventarioSeleccionado != null) {
            inventarioSeleccionado = valoresActualizarInventario(inventarioSeleccionado);
            if (controladorInventario.actualizarInventario(inventarioSeleccionado)) {

                JOptionPane.showMessageDialog(rootPane, "Producto editado con exito del sitema.");
                limpiarInventario();
                inventarioSeleccionado = null;
                modelTableInventario.setInventarios(controladorInventario.obtenerProductosInventario());
                modelTableInventario.fireTableDataChanged();
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se puede editar la Producto", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnInventarioEditarActionPerformed

    private void btnInventarioCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioCrearActionPerformed
        // TODO add your handling code here:
        Inventario i = new Inventario();
        i.setCodProducto(txtInventarioCodProducto.getText());
        i.setCanProductos(Integer.parseInt(txtInventarioCantidadProdcutos.getText()));
        i.setDescripcion(txtInventarioDescripcion.getText());
        i.setPrecioCompraSinIva(Double.parseDouble(txtPrecioCompra.getText().replace('.', ',')));
        i.setPrecioCompraConIva(Double.parseDouble(txtPrecioConIva.getText()));
        i.setPrecioMayorista(Double.parseDouble(txtPrecioMayorista.getText()));
        i.setPrecioClienteFijo(Double.parseDouble(txtPrecioClienteFijo.getText()));
        i.setPrecioClienteNormal(Double.parseDouble(txtPrecioClienteNormal.getText()));
        controladorInventario.registrarProducto(i);
        limpiarInventario();
        modelTableInventario.setInventarios(controladorInventario.obtenerProductosInventario());
        modelTableInventario.fireTableDataChanged();
    }//GEN-LAST:event_btnInventarioCrearActionPerformed

    private void btnInventaripBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventaripBusquedaActionPerformed
        // TODO add your handling code here:
        System.out.println("Combo" + comboBoxInventarioBusqueda.getSelectedIndex());
        switch (comboBoxInventarioBusqueda.getSelectedIndex()) {
            case 0://Codigo
                modelTableInventario.setInventarios(controladorInventario.obtenerProductosInventarioCodigo(txtInventarioBusqueda.getText()));
                modelTableInventario.fireTableDataChanged();
                break;
            case 1://7Descripcion
                modelTableInventario.setInventarios(controladorInventario.obtenerProductosInventarioDescripcion(txtInventarioBusqueda.getText()));
                modelTableInventario.fireTableDataChanged();
                break;
        }
    }//GEN-LAST:event_btnInventaripBusquedaActionPerformed

    private void txtParametroBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtParametroBusquedaKeyReleased
        // TODO add your handling code here:
        buscarCliente(txtParametroBusqueda.getText());
    }//GEN-LAST:event_txtParametroBusquedaKeyReleased

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        gestionPersona.limpiarCamposPersona();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    //Eliminar una persona de la base de datos.
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:asdasd
        if (personaEditarEliminar != null) {
            if (controladorPersona.eliminar(personaEditarEliminar)) {
                JOptionPane.showMessageDialog(rootPane, "Persona eliminada con éxito del sitema.");
                gestionPersona.limpiarCamposPersona();
                actualizarTodaLaTablaPersonas();
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se puede eliminar la persona seleccionada.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No hay persona seleccionada para eliminar.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:

        if (personaEditarEliminar == null) {
            JOptionPane.showMessageDialog(rootPane, "No hay una persona seleccionada para editar", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Persona personaEditarLocal = gestionPersona.guardarEditar(true);
        if (personaEditarLocal != null) {
            personaEditarLocal.setFechaRegistro(personaEditarEliminar.getFechaRegistro());
            personaEditarLocal.setIdPersona(personaEditarEliminar.getIdPersona());
            if (controladorPersona.actualizar(personaEditarLocal)) {
                JOptionPane.showMessageDialog(rootPane, "Persona editada con exito del sitema.");
                gestionPersona.limpiarCamposPersona();
                personaEditarEliminar = null;
                actualizarTodaLaTablaPersonas();
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se puede editar la persona", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (controladorPersona.getPersonaCedula(txtCedula.getText()) != null) {
            JOptionPane.showMessageDialog(rootPane, "La persona con ese número de cédula ya se encuentra registrada en el sistema.");
        } else {
            Persona personaGuardar = gestionPersona.guardarEditar(false);
            if (jDateFechaNacimiento.getDate() != null) {
                personaGuardar.setFechaNacimiento(jDateFechaNacimiento.getDate());
            }
            if (personaGuardar != null) {
                if (controladorPersona.registrarPersona(personaGuardar)) {
                    JOptionPane.showMessageDialog(rootPane, "Persona registrada en el sistema.");
                    gestionPersona.limpiarCamposPersona();
                    actualizarTodaLaTablaPersonas();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "No se puede guardar la persona", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jrbPassaporteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jrbPassaporteItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            jrbCedula.setSelected(false);
        }
    }//GEN-LAST:event_jrbPassaporteItemStateChanged

    private void jrbCedulaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jrbCedulaItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            jrbPassaporte.setSelected(false);
        }
    }//GEN-LAST:event_jrbCedulaItemStateChanged

    private void txtCedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCedulaFocusLost
        if (jrbCedula.isSelected()) {
            if (txtCedula.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "El campo cedula no tiene datos.", "ERROR", JOptionPane.ERROR_MESSAGE);
                // Sirve para ubicar el cursor en un campo vacio.
            } else if (!utilidades.validadorDeCedula(txtCedula.getText())) {
                JOptionPane.showMessageDialog(this, "la cedula ingresada no es valida", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
        if (jrbPassaporte.isSelected()) {
            if (txtCedula.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "El campo DNI no tiene datos.", "ERROR", JOptionPane.ERROR_MESSAGE);
                // Sirve para ubicar el cursor en un campo vacio.
            }
        }
    }//GEN-LAST:event_txtCedulaFocusLost

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        AcercaDe dialog = new AcercaDe(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void txtPrecioConIvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioConIvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioConIvaActionPerformed

    private void txtPrecioClienteNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioClienteNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioClienteNormalActionPerformed

    private void txtPrecioCompraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioCompraKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isDigit(c) || c == '.') {

        } else {
            JOptionPane.showMessageDialog(this, "El campo solo admite números.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtPrecioCompraKeyPressed

    private void txtPrecioCompraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecioCompraFocusLost
        double valor = precioConIva(Double.parseDouble(txtPrecioCompra.getText()));
        txtPrecioConIva.setText(String.valueOf(valor));
        txtPrecioMayorista.setText(String.valueOf(precioMayorista(Double.parseDouble(txtPrecioConIva.getText()))));
        txtPrecioClienteFijo.setText(String.valueOf(precioClienteFijo(Double.parseDouble(txtPrecioConIva.getText()))));
        txtPrecioClienteNormal.setText(String.valueOf(precioNormal(Double.parseDouble(txtPrecioConIva.getText()))));
    }//GEN-LAST:event_txtPrecioCompraFocusLost

    private void btnElimnarProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimnarProveedoresActionPerformed
        // TODO add your handling code here:
        if (proveedorSelect == null) {
            JOptionPane.showMessageDialog(this, "No hay un proveedor seleccionado para elimnar.", "Información", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (controladorProveedor.eliminarProveedores(proveedorSelect)) {
            JOptionPane.showMessageDialog(this, "Proveedor elimnado con éxito del sistema", "Información", JOptionPane.INFORMATION_MESSAGE);
            limpiarCamposProveedor();
            actualizarTodaLaTablaProveedores();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo eliminar el proveedor.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnElimnarProveedoresActionPerformed

    private void btnLimpiarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarProveedorActionPerformed
        // TODO add your handling code here:
        limpiarCamposProveedor();
    }//GEN-LAST:event_btnLimpiarProveedorActionPerformed

    private void btnEditarProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProveedoresActionPerformed
        // TODO add your handling code here:
        if (proveedorSelect == null) {
            JOptionPane.showMessageDialog(this, "No hay un proveedor seleccionado para editar.", "Información", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        proveedorSelect.setRuc(txtRucProveedores.getText());
        proveedorSelect.setRazonSocial(txtRazonSocialProveedores.getText());
        proveedorSelect.setTipoActividad(txtTipoActividadProveedores.getText());
        proveedorSelect.setNombreRepresentanteLegal(txtNombreRepresentateLegalProveedores.getText());
        proveedorSelect.setApellidosRepresentanteLegal(txtApellidosRepresentateLegalProveedores.getText());
        proveedorSelect.setTelefono(txtTelefonoProveedores.getText());
        proveedorSelect.setCorreo(txtCorrreoProveedores.getText());
        proveedorSelect.setFechaRegistro(new Date());
        proveedorSelect.setFechaVencimientoDeuda(null);
        if (controladorProveedor.actualizarProveedores(proveedorSelect)) {
            JOptionPane.showMessageDialog(this, "Proveedor editado con éxito del sistema", "Información", JOptionPane.INFORMATION_MESSAGE);
            limpiarCamposProveedor();
            actualizarTodaLaTablaProveedores();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo editar el proveedor.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarProveedoresActionPerformed

    private void btnLimpiarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarInventarioActionPerformed
        // TODO add your handling code here:
        limpiarInventario();
    }//GEN-LAST:event_btnLimpiarInventarioActionPerformed

    private void txtBuscarClienteNotaVentaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarClienteNotaVentaFocusLost
        // TODO add your handling code here:
        if (!txtBuscarClienteNotaVenta.getText().isEmpty()) {
            Persona personaCedula = controladorPersona.getPersonaCedula(txtBuscarClienteNotaVenta.getText());
            if (personaCedula != null) {
                txtNombreClienteNotaVenta.setText(personaCedula.getNombreCompletos());
                txtDireccionNotaVenta.setText(personaCedula.getDireccion());
                txtTelefonoNotaVenta.setText(personaCedula.getTelefono());
                txtFechaVentaNotaVenta.setText(new Date().toString());
            } else {
                JOptionPane.showMessageDialog(this, "El número de cédula del cliente no se encuentra en el sistema, verifíque o ingrese el cliente al sistema.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_txtBuscarClienteNotaVentaFocusLost

    private void txtBuscarClienteNotaVentaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarClienteNotaVentaFocusGained
        txtNombreClienteNotaVenta.setText("");
        txtDireccionNotaVenta.setText("");
        txtTelefonoNotaVenta.setText("");
        txtFechaVentaNotaVenta.setText("");
    }//GEN-LAST:event_txtBuscarClienteNotaVentaFocusGained
    public void limpiarInventario() {
        inventarioSeleccionado = null;
        txtInventarioCodProducto.setText("");
        txtInventarioCantidadProdcutos.setText("");
        txtInventarioDescripcion.setText("");
        txtPrecioCompra.setText("");
        txtPrecioConIva.setText("");
        txtPrecioMayorista.setText("");
        txtPrecioClienteFijo.setText("");
        txtPrecioClienteNormal.setText("");
    }

    public void limpiarCamposProveedor() {
        proveedorSelect = null;
        txtRucProveedores.setText("");
        txtRazonSocialProveedores.setText("");
        txtTipoActividadProveedores.setText("");
        txtNombreRepresentateLegalProveedores.setText("");
        txtApellidosRepresentateLegalProveedores.setText("");
        txtTelefonoProveedores.setText("");
        txtCorrreoProveedores.setText("");
    }

    public double precioConIva(double precioSinIva) {
        return utilidades.dosDecimales((precioSinIva * 0.12) + precioSinIva);
    }

    public double precioMayorista(double precioSinIva) {
        return utilidades.dosDecimales((precioSinIva * 0.10) + precioSinIva);
    }

    public double precioClienteFijo(double precioSinIva) {
        return utilidades.dosDecimales((precioSinIva * 0.12) + precioSinIva);
    }

    public double precioNormal(double precioSinIva) {
        return utilidades.dosDecimales((precioSinIva * 0.15) + precioSinIva);
    }

    private Inventario valoresActualizarInventario(Inventario i) {
        i.setCodProducto(txtInventarioCodProducto.getText());
        i.setCanProductos(Integer.parseInt(txtInventarioCantidadProdcutos.getText()));
        i.setDescripcion(txtInventarioDescripcion.getText());
        i.setPrecioCompraSinIva(Double.parseDouble(txtPrecioCompra.getText()));
        i.setPrecioCompraConIva(Double.parseDouble(txtPrecioConIva.getText()));
        i.setPrecioMayorista(Double.parseDouble(txtPrecioMayorista.getText()));
        i.setPrecioClienteFijo(Double.parseDouble(txtPrecioClienteFijo.getText()));
        i.setPrecioClienteNormal(Double.parseDouble(txtPrecioClienteNormal.getText()));
        return i;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionContable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionContable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionContable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionContable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionContable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarProveedor;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEditarProveedores;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnElimnarProveedores;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarProveedores;
    private javax.swing.JButton btnInventarioCrear;
    private javax.swing.JButton btnInventarioEditar;
    private javax.swing.JButton btnInventarioEliminar;
    private javax.swing.JButton btnInventaripBusqueda;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiarInventario;
    private javax.swing.JButton btnLimpiarProveedor;
    private javax.swing.JComboBox<String> comboBoxInventarioBusqueda;
    private javax.swing.JComboBox<String> comboParametroBusqueda;
    private javax.swing.JComboBox<String> comboParamtroBusquedaProveedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateFechaNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollCliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JComboBox<String> jcboxGenero;
    private javax.swing.JRadioButton jrbCedula;
    private javax.swing.JRadioButton jrbPassaporte;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblBuscarCliente;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuItem menuBuscarPersona;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenuBar menuGeneral;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JPanel panelCliente;
    private javax.swing.JPanel panelCuerpoRegistro;
    private javax.swing.JPanel panelInventario;
    private javax.swing.JPanel panelProveedores;
    private javax.swing.JPanel panelVenta;
    private javax.swing.JTabbedPane tabGeneral;
    private javax.swing.JTable tablaCliente;
    private javax.swing.JTable tablaProvedores;
    private javax.swing.JScrollPane tblInventario;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtApellidosRepresentateLegalProveedores;
    private javax.swing.JTextField txtBuscarClienteNotaVenta;
    private javax.swing.JTextField txtCantidadProuductoNotaVenta;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtCorrreoProveedores;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDireccionNotaVenta;
    private javax.swing.JTextField txtFechaVentaNotaVenta;
    private javax.swing.JTextField txtIdProductoNotaVenta;
    private javax.swing.JTextField txtInventarioBusqueda;
    private javax.swing.JTextField txtInventarioCantidadProdcutos;
    private javax.swing.JTextField txtInventarioCodProducto;
    private javax.swing.JTextField txtInventarioDescripcion;
    private javax.swing.JTextField txtNombreClienteNotaVenta;
    private javax.swing.JTextField txtNombreRepresentateLegalProveedores;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtParametroBusqueda;
    private javax.swing.JTextField txtParametroBusquedaProveedor;
    private javax.swing.JTextField txtPrecioClienteFijo;
    private javax.swing.JTextField txtPrecioClienteNormal;
    private javax.swing.JTextField txtPrecioCompra;
    private javax.swing.JTextField txtPrecioConIva;
    private javax.swing.JTextField txtPrecioMayorista;
    private javax.swing.JTextField txtRazonSocialProveedores;
    private javax.swing.JTextField txtRucProveedores;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefonoNotaVenta;
    private javax.swing.JTextField txtTelefonoProveedores;
    private javax.swing.JTextField txtTipoActividadProveedores;
    private javax.swing.JLabel txtTituloCliente;
    private javax.swing.JLabel txtTituloInventario;
    private javax.swing.JLabel txtTituloProveedores;
    private javax.swing.JLabel txtTituloVenta;
    // End of variables declaration//GEN-END:variables

    @Override
    public void clickPersona(Persona p) {
        txtCedula.setText(p.getCedula());
        txtNombres.setText(p.getNombre());
        txtApellidos.setText(p.getApellidos());
        txtDireccion.setText(p.getDireccion());
        txtTelefono.setText(p.getTelefono());
        txtCorreo.setText(p.getCorreo());
        jcboxGenero.setSelectedIndex(p.getGenero());
        jDateFechaNacimiento.setDate(p.getFechaNacimiento());
        personaEditarEliminar = p;

    }

    private void buscarCliente(String text) {
        System.out.println("Text:" + text);
        System.out.println("ObjetoSelc:" + comboParametroBusqueda.getSelectedIndex());
        switch (comboParametroBusqueda.getSelectedIndex()) {
            case 0://Cedula
                modelTablePersonaV2.setPersonas(controladorPersona.getPersonaCedulaLista(text));
                modelTablePersonaV2.fireTableDataChanged();
                break;
            case 1://nombre
                modelTablePersonaV2.setPersonas(controladorPersona.getPersonaNombre(text));
                modelTablePersonaV2.fireTableDataChanged();
                break;
            case 2://apellido
                break;
        }
    }

    @Override
    public void clickProveedores(Proveedores p) {
        proveedorSelect = p;
        txtRucProveedores.setText(p.getRuc());
        txtRazonSocialProveedores.setText(p.getRazonSocial());
        txtTipoActividadProveedores.setText(p.getTipoActividad());
        txtNombreRepresentateLegalProveedores.setText(p.getNombreRepresentanteLegal());
        txtApellidosRepresentateLegalProveedores.setText(p.getApellidosRepresentanteLegal());
        txtTelefonoProveedores.setText(p.getTelefono());
        txtCorrreoProveedores.setText(p.getCorreo());

    }

    @Override
    public void clickInventario(Inventario i) {
        inventarioSeleccionado = i;
        txtInventarioCodProducto.setText(i.getCodProducto());
        txtInventarioCantidadProdcutos.setText(String.valueOf(i.getCanProductos()));
        txtInventarioDescripcion.setText(i.getDescripcion());
        txtPrecioCompra.setText(String.valueOf(i.getPrecioCompraSinIva()));
        txtPrecioConIva.setText(String.valueOf(i.getPrecioCompraConIva()));
        txtPrecioMayorista.setText(String.valueOf(i.getPrecioMayorista()));
        txtPrecioClienteFijo.setText(String.valueOf(i.getPrecioClienteFijo()));
        txtPrecioClienteNormal.setText(String.valueOf(i.getPrecioClienteNormal()));
    }

}
